# -*- coding: utf-8 -*-
"""Question3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzVDU_HdzGw_Fj0KAGUkgQpNB1EEggVK
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

co2 = pd.read_csv("/content/drive/MyDrive/Dataset/GCB2022v27_MtCO2_flat.csv")
energy = pd.read_csv("/content/drive/MyDrive/Dataset/World_Energy_Consumption.csv")

# Comprehensive standardized country name mapping
country_fix = {
    'United States': 'USA',
    'United States of America': 'USA',
    'Russian Federation': 'Russia',
    'Viet Nam': 'Vietnam',
    'Republic of Korea': 'South Korea',
    'Korea, Republic of': 'South Korea',
    'Democratic People\'s Republic of Korea': 'North Korea',
    'North Korea, Democratic People\'s Republic of': 'North Korea',
    'United Kingdom of Great Britain and Northern Ireland': 'UK',
    'United Kingdom': 'UK',
    'Iran (Islamic Republic of)': 'Iran',
    'Venezuela (Bolivarian Republic of)': 'Venezuela',
    'Syrian Arab Republic': 'Syria',
    'Lao People\'s Democratic Republic': 'Laos',
    'Republic of Moldova': 'Moldova',
    'Czechia': 'Czech Republic',
    'Türkiye': 'Turkey',
    'Taiwan, Province of China': 'Taiwan',
    'Hong Kong SAR': 'Hong Kong',
    'Macao SAR': 'Macau',
    'Macedonia, The Former Yugoslav Republic of': 'North Macedonia',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Congo, Democratic Republic of the': 'DR Congo',
    'Democratic Republic of the Congo': 'DR Congo',
    'Congo': 'Republic of the Congo',
    'Congo, Republic of the': 'Republic of the Congo',
    'Tanzania, United Republic of': 'Tanzania',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Brunei Darussalam': 'Brunei',
    'Myanmar (Burma)': 'Myanmar',
    'Cape Verde': 'Cabo Verde',
    'Swaziland': 'Eswatini',
    'Palestine, State of': 'Palestine',
    'Micronesia (Federated States of)': 'Micronesia',
    'Saint Kitts and Nevis': 'St. Kitts and Nevis',
    'Saint Lucia': 'St. Lucia',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'The Gambia': 'Gambia',
    'Bahamas, The': 'Bahamas',
    'Gambia, The': 'Gambia',
    'Timor-Leste': 'East Timor',
    'Antigua and Barbuda': 'Antigua & Barbuda',
    'Bosnia and Herzegovina': 'Bosnia & Herzegovina',
    'Trinidad and Tobago': 'Trinidad & Tobago',
    'Sao Tome and Principe': 'São Tomé and Príncipe',
    'Guinea-Bissau': 'Guinea Bissau',
    'Dominican Rep.': 'Dominican Republic',
    'Solomon Is.': 'Solomon Islands',
    'Marshall Is.': 'Marshall Islands',
    'Cabo Verde': 'Cape Verde',
    'Burma': 'Myanmar',
    'Libyan Arab Jamahiriya': 'Libya',
    'Slovak Republic': 'Slovakia',
    'Bahamas': 'The Bahamas',
    'Gambia': 'The Gambia',
    'Sudan (Former)': 'Sudan',
    'South Sudan (Republic of)': 'South Sudan',
    'Yemen, Rep.': 'Yemen',
    'Yemen, Republic of': 'Yemen',
    'Egypt, Arab Rep.': 'Egypt',
    'China, Hong Kong SAR': 'Hong Kong',
    'China, Macao SAR': 'Macau',
    'China, Taiwan Province of China': 'Taiwan',
    'Channel Islands': 'Channel Islands',
    'Kosovo (Disputed Territory)': 'Kosovo',
    'Reunion': 'Réunion',
    'Eswatini (Swaziland)': 'Eswatini',
    'St. Vincent & Grenadines': 'St. Vincent and the Grenadines',
    'St. Kitts & Nevis': 'St. Kitts and Nevis',
    'St. Lucia': 'Saint Lucia',
    'Macau SAR': 'Macau',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Dem. Rep. Congo': 'DR Congo',
    'Cabo Verde': 'Cape Verde',
    'Ivory Coast': 'Côte d\'Ivoire'
}

# Standardize column names
co2.columns = co2.columns.str.strip().str.lower()
energy.columns = energy.columns.str.strip().str.lower()

# Check names for confirmation
print("CO₂ columns:", co2.columns[:10].tolist())
print("Energy columns:", energy.columns[:10].tolist())

# Apply country name standardization
co2['country'] = co2['country'].replace(country_fix)
energy['country'] = energy['country'].replace(country_fix)

# Confirm sample
print("Unique country names in CO₂ data:", co2['country'].nunique())
print("Unique country names in Energy data:", energy['country'].nunique())

import numpy as np

# --- Step 4: Clean both datasets without dropping rows ---

for df in (co2, energy):
    # 1) Normalize obvious placeholders to NaN
    df.replace([-9999, -999, -99, 'NaN', 'nan', 'N/A', 'n/a'], np.nan, inplace=True)

    # 2) Ensure correct dtypes
    df['year'] = pd.to_numeric(df['year'], errors='coerce')

    # 3) Work only on numeric columns
    num_cols = df.select_dtypes(include=[np.number]).columns

    # 4) Negative numbers cannot be valid shares/emissions -> set to NaN
    df[num_cols] = df[num_cols].mask(df[num_cols] < 0)

    # 5) Sort for time-wise operations
    df.sort_values(['country', 'year'], inplace=True)
    df.reset_index(drop=True, inplace=True)

    # 6) Country-wise linear interpolation (both directions)
    df[num_cols] = (
        df.groupby('country', group_keys=False)[num_cols]
          .apply(lambda g: g.interpolate(method='linear', limit_direction='both'))
    )

    # 7) Country-wise forward/back fill for any remaining gaps
    df[num_cols] = df.groupby('country')[num_cols].ffill()
    df[num_cols] = df.groupby('country')[num_cols].bfill()

co2 = co2[(co2['year'] >= 1950) & (co2['year'] <= 2022)]
energy = energy[(energy['year'] >= 1950) & (energy['year'] <= 2022)]

merged = pd.merge(co2, energy, on=['country', 'year'], how='inner')
print("✅ Merge successful! Shape:", merged.shape)

import pandas as pd

# 0) Make sure column names are normalized
merged.columns = merged.columns.str.strip().str.lower()

# 1) Map common aliases -> canonical names (only renames if the key exists)
rename_map = {
    # CO2 dataset aliases
    'total': 'co2_total',
    'per capita': 'co2_per_capita',
    'coal': 'co2_from_coal',
    'oil': 'co2_from_oil',
    'gas': 'co2_from_gas',
    # Sometimes OWID-style names
    'co2': 'co2_total',
    'co2_per_capita': 'co2_per_capita',
    # Energy dataset (usually already these)
    'renewables_share_energy': 'renewables_share_energy',
    'fossil_share_energy': 'fossil_share_energy',
    'low_carbon_share_energy': 'low_carbon_share_energy',
    'energy_per_capita': 'energy_per_capita',
    'population': 'population',
    'gdp': 'gdp',
    'iso 3166-1 alpha-3': 'iso_code'
}
rename_map_active = {k:v for k,v in rename_map.items() if k in merged.columns}
merged.rename(columns=rename_map_active, inplace=True)

# 2) Define the columns we want to KEEP
keep_cols = [
    'country','year','iso_code',                # keys/meta
    'co2_total','co2_per_capita',               # main CO2
    'co2_from_coal','co2_from_oil','co2_from_gas',  # sources (useful context)
    'renewables_share_energy','fossil_share_energy','low_carbon_share_energy',  # energy mix
    'energy_per_capita','gdp','population'      # controls
]

# 3) Keep only those that actually exist; drop everything else
present_keep = [c for c in keep_cols if c in merged.columns]
dropped_cols = [c for c in merged.columns if c not in present_keep]

slim = merged[present_keep].copy()

print("Kept columns ({}):".format(len(present_keep)), present_keep)
print("Dropped columns ({}):".format(len(dropped_cols)))
# If you want to see them, uncomment:
# print(dropped_cols)

# 4) Sanity checks (rows unchanged)
print("Rows unchanged:", len(slim)==len(merged), "| rows =", len(slim))

# 5) Save slim dataset
out_path = "/content/drive/MyDrive/Dataset/final_merged_energy_co2_SLIM.csv"
slim.to_csv(out_path, index=False)
print("✅ Saved slim dataset ->", out_path)

import numpy as np

def pct_bad(series, cond):
    s = series.copy()
    return float((cond(s)).mean()*100)

problems = {}

if 'renewables_share_energy' in merged:
    problems['renewables_lt0_%'] = pct_bad(merged['renewables_share_energy'], lambda s: s<0)
    problems['renewables_gt100_%'] = pct_bad(merged['renewables_share_energy'], lambda s: s>100)

if 'fossil_share_energy' in merged:
    problems['fossil_lt0_%'] = pct_bad(merged['fossil_share_energy'], lambda s: s<0)
    problems['fossil_gt100_%'] = pct_bad(merged['fossil_share_energy'], lambda s: s>100)

if 'co2_total' in merged:
    problems['co2_total_negative_%'] = pct_bad(merged['co2_total'], lambda s: s<0)

print("Out-of-bound checks (% of rows):")
for k,v in problems.items():
    print(f"  {k}: {v:.4f}%")

import matplotlib.pyplot as plt

def sanity_plot(country, y0=1980):
    m = merged[(merged['country'] == country) & (merged['year'] >= y0)].copy()
    if m.empty:
        print(f"No data for {country}")
        return

    fig, ax1 = plt.subplots(figsize=(8, 4))
    lines, labels = [], []

    # CO2 line (blue, left axis)
    if 'co2_total' in m.columns:
        l1, = ax1.plot(m['year'], m['co2_total'],
                       linewidth=2, label='CO₂ total (left axis)')
        ax1.set_ylabel('CO₂ total (Mt)')
        lines.append(l1); labels.append(l1.get_label())

    ax1.set_xlabel('Year')

    # Renewables line (orange, right axis)
    ax2 = ax1.twinx()
    if 'renewables_share_energy' in m.columns:
        l2, = ax2.plot(m['year'], m['renewables_share_energy'],
                       color='tab:orange', linewidth=2,
                       label='Renewables share (right axis)')
        ax2.set_ylabel('Renewables share (%)')
        lines.append(l2); labels.append(l2.get_label())

    # One legend for both axes
    ax1.legend(lines, labels, loc='upper left')

    plt.title(f"Merge sanity – {country}")
    fig.tight_layout()
    plt.show()

for ctry in ['USA', 'UK', 'India', 'China']:
    sanity_plot(ctry)

import numpy as np
import pandas as pd

# Use your merged/slim DataFrame name here
df = merged.copy()   # or: df = slim.copy()

# 1) Normalize headers
df.columns = df.columns.str.strip().str.lower()

# 2) Required columns present?
must_have = ['country','year','co2_total','co2_per_capita',
             'renewables_share_energy','fossil_share_energy',
             'energy_per_capita','gdp','population']
print("Missing:", [c for c in must_have if c not in df.columns])

# 3) Create low_carbon if absent
if 'low_carbon_share_energy' not in df.columns and 'fossil_share_energy' in df.columns:
    df['low_carbon_share_energy'] = 100 - df['fossil_share_energy']

# 4) Year window with good overlap
df = df[(df['year'] >= 1950) & (df['year'] <= 2022)].copy()

# 5) Final sanity
print("Shape:", df.shape)
print("Years:", int(df['year'].min()), "→", int(df['year'].max()))
print("Countries:", df['country'].nunique())
df.head(3)

import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
sns.set(style="whitegrid", rc={'figure.dpi':120})

core_cols = [
    'co2_total','co2_per_capita','renewables_share_energy','fossil_share_energy',
    'low_carbon_share_energy','energy_per_capita','gdp','population'
]

desc_global = df[core_cols].describe().T
display(desc_global)

df['decade'] = (df['year']//10)*10
desc_by_decade = df.groupby('decade')[core_cols].agg(['count','mean','median','std','min','max'])
display(desc_by_decade.head())

plt.figure(figsize=(7.5,6))
sns.heatmap(df[core_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Global correlation (all rows)")
plt.tight_layout(); plt.show()

country_means = df.groupby('country')[core_cols].mean().dropna()
plt.figure(figsize=(7.5,6))
sns.heatmap(country_means.corr(), annot=True, fmt=".2f", cmap="coolwarm", square=True)
plt.title("Correlation on country means")
plt.tight_layout(); plt.show()

from scipy.stats import pearsonr, spearmanr
import statsmodels.api as sm

def analyze_relation(df, x, y, title="", logx=False, logy=False, sample=None):
    data = df[[x, y, 'country', 'year']].dropna().copy()
    if sample and len(data) > sample:
        data = data.sample(sample, random_state=42)
    X = data[x].astype(float)
    Y = data[y].astype(float)
    if logx:
        X = np.log10(np.clip(X, 0, None) + 1)
    if logy:
        Y = np.log10(np.clip(Y, 0, None) + 1)
    sm.OLS(Y, sm.add_constant(X)).fit()
    plt.figure(figsize=(7.2, 5))
    sns.regplot(x=X, y=Y, scatter_kws={'alpha': 0.25, 's': 12}, line_kws={'lw': 2})
    plt.xlabel(("log10(" + x + "+1)") if logx else x)
    plt.ylabel(("log10(" + y + "+1)") if logy else y)
    plt.title(title or f"{x} vs {y}")
    plt.tight_layout()
    plt.show()

results = {}
results['1_renewables_vs_co2'] = analyze_relation(df, 'renewables_share_energy', 'co2_total',
    'Renewable Share vs Total CO₂', logx=False, logy=True, sample=40000)
results['2_gdp_vs_co2'] = analyze_relation(df, 'gdp', 'co2_total',
    'GDP vs Total CO₂', logx=True, logy=True, sample=40000)
results['3_energy_pc_vs_co2_pc'] = analyze_relation(df, 'energy_per_capita', 'co2_per_capita',
    'Energy per Capita vs CO₂ per Capita', logx=True, logy=True, sample=40000)
results['4_fossil_vs_renewables'] = analyze_relation(df, 'fossil_share_energy', 'renewables_share_energy',
    'Fossil Share vs Renewable Share', logx=False, logy=False, sample=40000)
results['5_lowcarbon_vs_co2'] = analyze_relation(df, 'low_carbon_share_energy', 'co2_total',
    'Low-Carbon Share vs Total CO₂', logx=False, logy=True, sample=40000)
results['6_population_vs_co2'] = analyze_relation(df, 'population', 'co2_total',
    'Population vs Total CO₂', logx=True, logy=True, sample=40000)

from scipy.stats import pearsonr, spearmanr
import statsmodels.api as sm

def analyze_relation(df, x, y, title="", logx=False, logy=False, sample=None):
    data = df[[x, y, 'country', 'year']].dropna().copy()
    if sample and len(data) > sample:
        data = data.sample(sample, random_state=42)
    X = data[x].astype(float)
    Y = data[y].astype(float)
    if logx:
        X = np.log10(np.clip(X, 0, None) + 1)
    if logy:
        Y = np.log10(np.clip(Y, 0, None) + 1)
    sm.OLS(Y, sm.add_constant(X)).fit()
    plt.figure(figsize=(7.2, 5))
    sns.regplot(x=X, y=Y, scatter_kws={'alpha': 0.25, 's': 12}, line_kws={'lw': 2})
    plt.xlabel(("log10(" + x + "+1)") if logx else x)
    plt.ylabel(("log10(" + y + "+1)") if logy else y)
    plt.title(title or f"{x} vs {y}")
    plt.tight_layout()
    plt.show()

results = {}
results['1_renewables_vs_co2'] = analyze_relation(df, 'renewables_share_energy', 'co2_total',
    'Renewable Share vs Total CO₂', logx=False, logy=True, sample=40000)
results['2_gdp_vs_co2'] = analyze_relation(df, 'gdp', 'co2_total',
    'GDP vs Total CO₂', logx=True, logy=True, sample=40000)
results['3_energy_pc_vs_co2_pc'] = analyze_relation(df, 'energy_per_capita', 'co2_per_capita',
    'Energy per Capita vs CO₂ per Capita', logx=True, logy=True, sample=40000)
results['4_fossil_vs_renewables'] = analyze_relation(df, 'fossil_share_energy', 'renewables_share_energy',
    'Fossil Share vs Renewable Share', logx=False, logy=False, sample=40000)
results['5_lowcarbon_vs_co2'] = analyze_relation(df, 'low_carbon_share_energy', 'co2_total',
    'Low-Carbon Share vs Total CO₂', logx=False, logy=True, sample=40000)
results['6_population_vs_co2'] = analyze_relation(df, 'population', 'co2_total',
    'Population vs Total CO₂', logx=True, logy=True, sample=40000)

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

pca_features = ['renewables_share_energy','fossil_share_energy','energy_per_capita','co2_per_capita','gdp']
pcadf = df.groupby('country')[pca_features].mean().dropna()

X = StandardScaler().fit_transform(pcadf.values)
pca = PCA(n_components=2, random_state=0).fit(X)
PC = pd.DataFrame(pca.transform(X), index=pcadf.index, columns=['PC1','PC2'])

print("Explained variance ratio:", pca.explained_variance_ratio_)

plt.figure(figsize=(7,5))
sns.scatterplot(x='PC1', y='PC2', data=PC, s=22, alpha=0.8)
plt.title('PCA: Country Energy & CO₂ Profiles'); plt.tight_layout(); plt.show()

data = df[['energy_per_capita','co2_per_capita']].dropna()
plt.figure(figsize=(7.5,5))
plt.hexbin(data['energy_per_capita'], data['co2_per_capita'], gridsize=40, mincnt=1)
plt.colorbar(label='Count')
plt.xlabel('Energy per Capita'); plt.ylabel('CO₂ per Capita')
plt.title('CO₂ per Capita vs Energy per Capita (hexbin density)')
plt.tight_layout(); plt.show()

cm = df.groupby('country')[['energy_per_capita','co2_per_capita']].mean().dropna()

plt.figure(figsize=(7.5,5))
sns.regplot(data=cm, x='energy_per_capita', y='co2_per_capita',
            scatter_kws={'alpha':0.7,'s':25}, line_kws={'lw':2})
plt.xlabel('Energy per Capita (mean per country)')
plt.ylabel('CO₂ per Capita (mean per country)')
plt.title('Country Means: CO₂ per Capita vs Energy per Capita')
plt.tight_layout(); plt.show()